### ISSUE TITLE
Update for media_player fails

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/addon-aircast#5]
# Problem/Motivation

> When I restart HA while sonos was streaming from airconnect, update for sonos fails

## Expected behavior

> Sonos updates

## Actual behavior

> 
```
Update for media_player.keuken fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 324, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/sonos.py", line 511, in update
    track_info = self._player.get_current_track_info()
  File "/usr/lib/python3.6/site-packages/soco/core.py", line 1219, in get_current_track_info
    index = trackinfo.find(' - ')
AttributeError: 'NoneType' object has no attribute 'find'
```

## Steps to reproduce

> restart HA while airconnect is streaming

**Comment by gieljnssns** [comment]
I'm sorry this issue is for airsonos
